include:
  - project: 'famedly/templates/ci-cd'
    ref: main
    file:
      - '/rust.yml'
      - '/docker.yml'

stages:
  - test
  - build
  - deploy

cargo-check:
  extends: .cargo_check

cargo-build-amd64:
  extends: .cargo_build
  script:
    - cargo build --release
    - mv config.sample.yaml ./target/release/config.yaml

cargo-build-armv7:
  extends: .cargo_build
  variables:
    RUST_ADDITIONAL_PACKAGES: "gcc-arm-linux-gnueabihf libc6-dev-armhf-cross"
  script:
    - mkdir .cargo && mv cargo/config .cargo/config
    - rustup target add armv7-unknown-linux-gnueabihf
    - rustup show
    - cargo build --target armv7-unknown-linux-gnueabihf --release
    - mv config.sample.yaml ./target/release/config.yaml
  artifacts:
    paths:
      - target/armv7-unknown-linux-gnueabihf/release/

cargo-build-aarch64:
  extends: .cargo_build
  variables:
    TARGET_CC: "/usr/bin/aarch64-linux-gnu-gcc-8"
    TARGET_AR: "/usr/bin/aarch64-linux-gnu-gcc-ar-8"
    RUST_ADDITIONAL_PACKAGES: "gcc-8-aarch64-linux-gnu libc6-dev-arm64-cross"
  script:
    - mkdir .cargo && mv cargo/config .cargo/config
    - rustup target add aarch64-unknown-linux-gnu
    - rustup show
    - cargo build --target aarch64-unknown-linux-gnu --release
    - mv config.sample.yaml ./target/release/config.yaml
  artifacts:
    paths:
      - target/aarch64-unknown-linux-gnu/release/

docker-releases:
  extends: .docker_releases
  needs: ["cargo-build-amd64"]

docker-releases-armv7:
  extends: .docker_releases
  needs: ["cargo-build-armv7"]
  variables:
    DOCKER_TAG: "${CI_COMMIT_TAG}-armv7"

docker-releases-aarch64:
  extends: .docker_releases
  needs: ["cargo-build-aarch64"]
  variables:
    DOCKER_TAG: "${CI_COMMIT_TAG}-aarch64"


docker-tags:
  extends: .docker_tags
  needs: ["cargo-build-amd64"]

docker-tags-armv7:
  extends: .docker_tags
  needs: ["cargo-build-armv7"]
  variables:
    DOCKER_TAG: "${CI_COMMIT_TAG}-armv7"

docker-tags-aarch64:
  extends: .docker_tags
  needs: ["cargo-build-aarch64"]
  variables:
    DOCKER_TAG: "${CI_COMMIT_TAG}-aarch64"


docker-branches-amd64:
  extends: .docker_branches
  needs: ["cargo-build-amd64"]

docker-branches-armv7:
  extends: .docker_branches
  needs: ["cargo-build-armv7"]
  variables:
    DOCKER_TAG: "${CI_COMMIT_REF_SLUG}-armv7"

docker-branches-aarch64:
  extends: .docker_branches
  needs: ["cargo-build-aarch64"]
  variables:
    DOCKER_TAG: "${CI_COMMIT_REF_SLUG}-aarch64"
