# Include our templates for rust and docker:
include:
  - project: 'famedly/company/devops/templates/ci-cd'
    ref: rust-v1
    file:
      - '/rust.yml'
  - project: 'famedly/company/devops/templates/ci-cd'
    ref: docker-v1
    file:
      - '/docker.yml'

# Different CI stages, that are shown as dots in the GitLab UI and
# are executed one after another
stages:
  - test
  - doc
  - deploy

# Check stage for formatting, lints and test checking
cargo-check:
  # Extend from the template
  extends: .cargo_check
  # Overwrite the script.
  # Optional, remove if not needed
  script:
    # Run these commands in order, so execute a script in the repository first
    - bash tests/setup.sh
    # Run the script that was in the template, that we overwrote
    - !reference [.cargo_check, script]

# Documentation pages generation and deployment to the GitLab UI.
# Only runs on the main branch.
pages:
  # just included (-> activated) from the template
  extends: .cargo_doc

# Build and release the docker container
# Only runs on the main branch.
docker-releases:
  # just included (-> activated) from the template
  extends: .docker_releases

# Build and release the docker container, tagging latest as well
# Only runs on the main branch.
docker-tags:
  # just included (-> activated) from the template
  extends: .docker_tags

# Build the docker container for any branch and
# release it with its commit hash
docker-branches:
  # just included (-> activated) from the template
  extends: .docker_branches
