stages:
  - test
  - build

cargo-test:
  stage: test
  image: rust:latest
  cache:
    paths:
      - target/
    key: build_cache
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo fmt -- --check
    - cargo check
    - cargo clippy
    - cargo test --all --verbose

cargo-build-amd64:
  stage: build
  image: rust:latest
  cache:
    paths:
      - target/
    key: build_cache
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --release
    - mv config.sample.toml ./target/release/config.toml
  artifacts:
    paths:
      - target/release/

cargo-build-armv7:
  stage: build
  image: rust:latest
  cache:
    paths:
      - target/
    key: build_cache
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
    - mv cargo/config /usr/local/cargo
    - rustup target add armv7-unknown-linux-gnueabihf

  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --target armv7-unknown-linux-gnueabihf --release
    - mv config.sample.toml ./target/release/config.toml
  artifacts:
    paths:
      - target/armv7-unknown-linux-gnueabihf/release/

cargo-build-aarch64:
  stage: build
  image: rust:latest
  variables:
    TARGET_CC: "/usr/bin/aarch64-linux-gnu-gcc-8"
    TARGET_AR: "/usr/bin/aarch64-linux-gnu-gcc-ar-8"
  cache:
    paths:
      - target/
    key: build_cache
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential gcc-8-aarch64-linux-gnu libc6-dev-arm64-cross
    - mv cargo/config /usr/local/cargo
    - rustup target add aarch64-unknown-linux-gnu

  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --target aarch64-unknown-linux-gnu --release
    - mv config.sample.toml ./target/release/config.toml
  artifacts:
    paths:
      - target/aarch64-unknown-linux-gnu/release/