repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: git@github.com:famedly/backend-pre-commit-templates.git
    rev: 548bf6ae934623c72e2e5f90e095b45259b6f4ba
    hooks:
    -   id: fmt
    -   id: clippy
-   repo: https://github.com/crate-ci/typos
    rev: typos-v0.10.26
    hooks:
    -   id: typos
