[package]
name = "matrix_push_gateway_tng"
version = "0.1.0"
authors = ["Christian Pauly <christian-pauly@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde = "1.0.123"
serde_json = "1.0.62"
config = "0.10.1"
fcm = "0.8.1"