[package]
name = "matrix-hedwig"
version = "1.3.0"
authors = ["Christian Pauly <c.pauly@famedly.com>", "Kateřina Churanová <k.churanova@famedly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a2 = "0.6.2"
axum = "0.4.2"
chrono = "0.4.19"
color-eyre = "0.5"
config = "0.10.1"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
fcm = { version = "0.9.1", features = ["rustls"], default-features = false }
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.2.0", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = "0.2.0"
prometheus = "0.11.0"

[patch.crates-io]
hyper-alpn = { path = "../../libraries/hyper-alpn" }

[build-dependencies]
vergen = "4.0.2"
