[package]
name = "matrix-hedwig"
version = "1.1.0"
authors = ["Christian Pauly <c.pauly@famedly.com>", "Kateřina Churanová <k.churanova@famedly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {version = "3", features = ["rustls"], default-features = false}
serde = "1.0.123"
serde_json = "1.0.62"
config = "0.10.1"
fcm = {version = "0.8.1", git = "https://github.com/kate-shine/fcm-rust.git", branch = "shine/reqwest-tokio-0.2", features = ["rustls"], default-features = false}
tracing = "0.1"
tracing-subscriber = "0.2.0"
actix-web-prom = "0.5.0"
prometheus = "0.11.0"

[build-dependencies]
vergen = "4.0.2"