version: '3'

services:
  hedwig:
    restart: "unless-stopped"
    image: docker-oss.nexus.famedly.de/hedwig
    build: .
    env_file: "config.properties"
    volumes:
      - ./fcm-auth.json:/opt/matrix-hedwig/fcm-auth.json
    ports:
      - 7022:7022/tcp
