version: '3'

services:
  hedwig:
    restart: "unless-stopped"
    image: docker-oss.nexus.famedly.de/hedwig:main
    volumes:
      - ./config.yaml:/opt/matrix-hedwig/config.yaml
      - ./fcm-auth.json:/opt/matrix-hedwig/fcm-auth.json
    ports:
      - 7022:7022/tcp
