apiVersion: apps/v1
kind: Deployment
metadata:
  name: hedwig-deployment
  labels:
    app: hedwig
spec:
  selector:
    matchLabels:
      app: hedwig
  replicas: 1
  template:
    metadata:
      labels:
        app: hedwig
    spec:
      containers:
        - name: hedwig
          image: docker-oss.nexus.famedly.de/hedwig:main
          # image: bash
          # command:
          #   - "sleep"
          #   - "1000"
          workingDir: "/opt/matrix-hedwig"
          ports:
            - containerPort: 7022
          volumeMounts:
            - name: config
              mountPath: /opt/matrix-hedwig/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: config
