version = 1

[[annotations]]
SPDX-FileCopyrightText = "Famedly GmbH"
SPDX-License-Identifier = "AGPL-3.0-or-later"
path = ["src/**", "build.rs", "tests/**"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Famedly GmbH"
SPDX-License-Identifier = "AGPL-3.0-or-later"
path = [
  "Cargo.toml",
  "Cargo.lock",
  "README.md",
  "CHANGELOG.md",
  "Dockerfile",
  "config.sample.yaml",
  "docker-compose.yml",
  "renovate.json",
  "rustfmt.toml",
  ".codecov.yaml",
  ".config/nextest.toml",
  ".gitignore",
  ".github/CODEOWNERS",
  ".github/workflows/docker.yml",
  ".github/workflows/main.yml",
  ".github/workflows/rust-workflow.yml",
]
precedence = "aggregate"
