
# cargo-vet audits file

[[audits.cfg-if]]
who = "Amanda Graven <amanda@graven.dev>"
criteria = "safe-to-deploy"
version = "1.0.0"
notes = """
A simple macro_rules convenience macro. Uses no unsafe code, does not leave any
obvious windows for underhanded use.
"""

[[audits.firebae-cm]]
who = "Amanda Graven <amanda@graven.dev>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "Contains only type definitions for use with serde deserialization"

[[audits.tinyvec_macros]]
who = "Amanda Graven <amanda@graven.dev>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = """
Simple macro_rules definition for providing a method imlementation on the
struct it's invoked on. Contains no unsafe code.
"""

