
# cargo-vet config file

[imports.famedly]
url = "https://gitlab.com/famedly/company/backend/templates/supply-chain/-/raw/main/audits.toml"

[[exemptions.addr2line]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "0.7.19"
criteria = "safe-to-run"

[[exemptions.android_system_properties]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.ansi_term]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.64"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.57"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.5.16"
criteria = "safe-to-deploy"

[[exemptions.axum-core]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.66"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.11.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.73"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.22"
criteria = "safe-to-deploy"

[[exemptions.color-eyre]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.color-spantrace]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.config]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.dashmap]]
version = "4.0.2"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.dirs-next]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys-next]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.dlv-list]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.enum-iterator]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.enum-iterator-derive]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.eyre]]
version = "0.6.8"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.firebae-cm]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.foreign-types]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.foreign-types-shared]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.24"
criteria = "safe-to-deploy"

[[exemptions.gcp_auth]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.6"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.getset]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.26.2"
criteria = "safe-to-deploy"

[[exemptions.git2]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.14"
criteria = "safe-to-deploy"

[[exemptions.headers]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.headers-core]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.http-range-header]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.20"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.23.0"
criteria = "safe-to-deploy"

[[exemptions.hyper-tls]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.47"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.indenter]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.1"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.jobserver]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.59"
criteria = "safe-to-deploy"

[[exemptions.json5]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.132"
criteria = "safe-to-deploy"

[[exemptions.libgit2-sys]]
version = "0.14.0+1.5.0"
criteria = "safe-to-deploy"

[[exemptions.libz-sys]]
version = "1.1.8"
criteria = "safe-to-deploy"

[[exemptions.linked-hash-map]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.8"
criteria = "safe-to-deploy"

[[exemptions.matchit]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.native-tls]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.1"
criteria = "safe-to-deploy"

[[exemptions.ntapi]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.num_threads]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.29.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.14.0"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.41"
criteria = "safe-to-deploy"

[[exemptions.openssl-macros]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.75"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-prometheus]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.ordered-multimap]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.owo-colors]]
version = "3.5.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.pathdiff]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.pest]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.pest_derive]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.pest_generator]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.pest_meta]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.prometheus]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.protobuf]]
version = "2.27.1"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.6.0"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.6.27"
criteria = "safe-to-run"

[[exemptions.remove_dir_all]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.reqwest]]
version = "0.11.11"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.ron]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.rust-ini]]
version = "0.18.0"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.rustc_version]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.20.6"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.20"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.sct]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.7.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.13"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.144"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.144"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.85"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.sha-1]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.sha1]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.99"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.sysinfo]]
version = "0.23.13"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.34"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.34"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.1.44"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.14"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.21.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-native-tls]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.23.4"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.5.9"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.tower-http]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.36"
criteria = "safe-to-deploy"

[[exemptions.tracing-appender]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.22"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.29"
criteria = "safe-to-deploy"

[[exemptions.tracing-error]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-futures]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.15"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.ucd-trie]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.unicode-bidi]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.unicode-normalization]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.vcpkg]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.vergen]]
version = "6.0.2"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.10.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.32"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.59"
criteria = "safe-to-deploy"

[[exemptions.webpki]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.winreg]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.yaml-rust]]
version = "0.4.5"
criteria = "safe-to-deploy"

