apiVersion: apps/v1
kind: Deployment
metadata:
  name: hedwig-deployment
  labels:
    app: hedwig
spec:
  selector:
    matchLabels:
      app: hedwig
  replicas: 1
  template:
    metadata:
      labels:
        app: hedwig
    spec:
      containers:
        - name: hedwig
          image: docker-oss.nexus.famedly.de/hedwig
          envFrom:
            - configMapRef:
                name: hedwig-config
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: /etc/secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 7022
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: secret-volume
          secret:
            secretName: fcm-auth
