apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: hedwig-config
    envs:
      - config.properties
secretGenerator:
  - name: fcm-auth
    files:
      - fcm-auth.json
